packages:
  - excalidraw-app
  - packages/*
  - examples/*
allowBuilds:
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
overrides:
  strip-ansi: 6.0.1
  '@typescript-eslint/eslint-plugin': 8.46.2
  '@typescript-eslint/parser': 8.46.2
